Set requirements to fixed versions to fix test.
In particular PyLD shoud be set to 1.0.5 becasue otherwise we will get a error :

pyld.jsonld.JsonLdError: ('Absolute IRI confused with prefix.',)

In version 2.x.x pyld is stricter in this respect. We probably need to revisit
the way we use JSON-LD . But for now this is fixed by using a older version
for PyLD